--COMANDO SELECT: REALIZAR A BUSCA  DE DADOS NAS COLUNAS DAS TABELAS

--SELECT PARA RETORNAR TODAS AS COLUNAS DA TABELA PERSON.PERSON
SELECT *
FROM person.person;

--SELECT PARA RETORNA A COLUNA TITLE DA TABELA PERSON.PERSON
SELECT Title
FROM person.person;

--SELECT PARA RETORNAR TODAS AS COLUNAS DA TABELA PERSON.EMAILADDRESS
SELECT *
FROM person.EmailAddress;

--SELECT PARA RETORNAR 2 COLUNAS DA TABELA PERSON.PERSON
SELECT FirstName,LastName
FROM person.person;